-- 071: client_strategy_spine — the per-client evolving doc that
-- audit packs, welcome briefings, and quarterly reports all render from.
--
-- The "spine" is the single source of strategic truth for a client.
-- Hybrid by design: free-text fields the strategist authors (positioning,
-- audience, stance, plays) live alongside a cached computed_snapshot of
-- the analytical signals. Artifacts read both layers so the strategic
-- narrative survives between deliverables instead of being regenerated
-- from raw data each time.
--
-- Why a separate table (not JSONB on channels):
--   - We want per-field updated_at timestamps for the "what's drifted
--     since you wrote this?" UX
--   - Active plays are list-like and queried/filtered
--   - Spine writes are frequent during a strategy session; we don't want
--     to bump every channels-row consumer when only the spine changes
--   - One row per client makes RLS, indexing, and cascade obvious

CREATE TABLE IF NOT EXISTS client_strategy_spine (
  client_id UUID PRIMARY KEY REFERENCES channels(id) ON DELETE CASCADE,

  -- Strategist-authored. NULL on creation; strategist fills in over time.
  positioning_hypothesis      TEXT,
  positioning_updated_at      TIMESTAMPTZ,
  audience_read               TEXT,
  audience_updated_at         TIMESTAMPTZ,
  quarterly_stance            TEXT,
  quarterly_stance_label      TEXT,    -- e.g. "Q2 2026"
  quarterly_stance_updated_at TIMESTAMPTZ,

  -- Active plays: experiments / initiatives the strategist is running.
  -- Shape per element:
  --   { id, name, hypothesis, started_at, status, evidence, notes }
  -- status ∈ in_flight | concluded_won | concluded_lost | paused
  active_plays                JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Computed snapshot: cached derivation of analytical signals
  -- (archetype mix, format mix, cadence, opportunities, outliers).
  -- Populated by refreshSnapshot(); read by audit pack renderer.
  -- Kept opaque here so the shape can evolve without a migration.
  computed_snapshot           JSONB,
  snapshot_computed_at        TIMESTAMPTZ,

  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Maintain updated_at on any write.
CREATE OR REPLACE FUNCTION client_strategy_spine_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_client_strategy_spine_updated_at ON client_strategy_spine;
CREATE TRIGGER trg_client_strategy_spine_updated_at
  BEFORE UPDATE ON client_strategy_spine
  FOR EACH ROW
  EXECUTE FUNCTION client_strategy_spine_touch_updated_at();

CREATE INDEX IF NOT EXISTS idx_spine_snapshot_computed_at
  ON client_strategy_spine(snapshot_computed_at DESC NULLS LAST);

COMMENT ON TABLE client_strategy_spine IS
  'Per-client strategic narrative. Free-text strategist fields + cached computed snapshot. Read by audit pack / briefing / quarterly artifacts so a clients narrative survives across deliverables.';
COMMENT ON COLUMN client_strategy_spine.positioning_hypothesis IS
  'Long-arc positioning thesis — typically reviewed quarterly, changes when stance pivots.';
COMMENT ON COLUMN client_strategy_spine.audience_read IS
  'Strategist read on who the channels real audience is. Sourced from client conversation, comments mining, retention patterns.';
COMMENT ON COLUMN client_strategy_spine.quarterly_stance IS
  'Stance the strategist is taking this quarter. The "what we are testing / doubling down on right now" field.';
COMMENT ON COLUMN client_strategy_spine.active_plays IS
  'JSONB array of experiments in flight or recently concluded. Each play: id, name, hypothesis, started_at, status, evidence, notes.';
COMMENT ON COLUMN client_strategy_spine.computed_snapshot IS
  'Cached analytical signals: archetype mix, format mix, cadence, opportunities, outliers. Regenerated by refreshSnapshot(); shape intentionally opaque to allow evolution.';
