-- 073: client_series_concepts — series-level ideation as a first-class
-- artifact in the dashboard.
--
-- The old Ideation tab generated standalone video ideas. Standalone-only
-- is a 2017 model; modern YouTube growth runs on series (binge watch-time,
-- session length, "next episode" anticipation, lower per-video creative
-- cost via templates). This table holds the strategic unit a strategist
-- actually plans against: a series concept with episodes underneath.
--
-- Lifecycle:
--   concept   → fresh idea (AI or user-submitted); browseable in Ideation
--   shelved   → strategist passed for now; can be revisited later
--   greenlit  → strategist committed; auto-creates an active play in the
--               client's Strategy Spine; episodes flow into Briefs pipeline
--   concluded → series completed (won/lost); becomes part of decision log
--
-- Why a separate table (not nested under client_strategy_spine.active_plays):
--   - Concepts have richer structure (episodes JSONB, format/cadence, source)
--   - Most concepts never get greenlit — we don't want shelved concepts
--     polluting the spine's active_plays view
--   - When a concept IS greenlit, we mirror a summary into active_plays
--     so the spine remains the single read surface

CREATE TABLE IF NOT EXISTS client_series_concepts (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id   UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,

  -- Source: how this concept entered the system
  source      TEXT NOT NULL DEFAULT 'ai' CHECK (source IN ('ai', 'user')),

  -- Lifecycle status
  status      TEXT NOT NULL DEFAULT 'concept'
    CHECK (status IN ('concept', 'shelved', 'greenlit', 'concluded')),
  status_changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Core fields
  title       TEXT NOT NULL,
  premise     TEXT,    -- the recurring promise / through-line
  format      TEXT,    -- e.g. "6-9 min long-form", "60-90s Shorts"
  cadence     TEXT,    -- e.g. "weekly", "biweekly", "drop all at once"
  episode_count INT,

  -- Episodes: array of { title, hook?, notes? }. Initially one-liners;
  -- the explore flow fills in more detail. Kept opaque for evolution.
  episodes    JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Strategic context the concept was generated against. Snapshot at
  -- creation so we can later see "this was greenlit when the stance was X"
  -- even if the spine moves on.
  rationale   TEXT,                          -- AI-generated "why this for this client"
  cohort_evidence JSONB,                     -- competitor patterns the concept drew on
  spine_snapshot TEXT,                       -- spine context block used at generation time

  -- Greenlight tracking
  greenlit_at TIMESTAMPTZ,
  active_play_id TEXT,                       -- id of the play in client_strategy_spine.active_plays

  -- Audit
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by  UUID                           -- auth.users id of the strategist who triggered it
);

CREATE INDEX IF NOT EXISTS idx_series_concepts_client_status
  ON client_series_concepts(client_id, status, status_changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_series_concepts_greenlit
  ON client_series_concepts(client_id, greenlit_at DESC)
  WHERE status = 'greenlit';

-- Bump updated_at on every write (matches the spine's pattern).
CREATE OR REPLACE FUNCTION client_series_concepts_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  IF (NEW.status IS DISTINCT FROM OLD.status) THEN
    NEW.status_changed_at = NOW();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_series_concepts_updated_at ON client_series_concepts;
CREATE TRIGGER trg_series_concepts_updated_at
  BEFORE UPDATE ON client_series_concepts
  FOR EACH ROW
  EXECUTE FUNCTION client_series_concepts_touch_updated_at();

COMMENT ON TABLE client_series_concepts IS
  'Series-level ideation: each row is a strategic unit (a series concept) with episode one-liners underneath. Status tracks the concept→explore→greenlight lifecycle. Greenlit concepts mirror a summary into client_strategy_spine.active_plays.';
COMMENT ON COLUMN client_series_concepts.source IS
  'ai = generated by Claude. user = seeded by the strategist (then fleshed out by Claude). Both go through the same lifecycle.';
COMMENT ON COLUMN client_series_concepts.spine_snapshot IS
  'The strategy spine context block used at generation time, snapshotted so historical decisions remain interpretable even after the spine evolves.';

-- ─── RLS ─────────────────────────────────────────────
ALTER TABLE client_series_concepts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read series concepts"
  ON client_series_concepts FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert series concepts"
  ON client_series_concepts FOR INSERT
  TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update series concepts"
  ON client_series_concepts FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated users can delete series concepts"
  ON client_series_concepts FOR DELETE
  TO authenticated USING (true);
